language: php

php:
  - 5.5

before_install:
  - sudo apt-get install -qq beanstalkd python-pip
  - sudo sed -i 's/^#\(\s*START\)/\1/' /etc/default/beanstalkd
  - sudo service beanstalkd start
  - sudo pip install fabric

before_script:
  - pear config-set preferred_state beta
  - pyrus install pear/PHP_CodeSniffer-1.5.6
  - phpenv rehash
  - (cd $(pyrus get php_dir | tail -1)/PHP/CodeSniffer/Standards && test -d Symfony2 || git clone -q https://github.com/ajayrungta/Symfony2-coding-standard.git Symfony2)
  - rm -rf /tmp/php-imagick-build
  - mkdir /tmp/php-imagick-build
  - (cd /tmp/php-imagick-build && wget https://github.com/mkoppanen/imagick/archive/3.2.0RC1.tar.gz -O - | tar xz && cd imagick-3.2.0RC1 && phpize && ./configure && make && make install)
  - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "\n" | pecl install apcu-beta
  - cp app/config/parameters_ci.yml app/config/parameters.yml
  - composer self-update
  - composer install -n
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

script: fab polish

cache:
  apt: true
  directories:
    - vendor

services:
  - memcached
  - rabbitmq

notifications:
  slack: practo:xKAtd798r2hyOPqP0fdlvqgt

addons:
  code_climate:
    repo_token: cf5da7d67ec5ce03785f9eea44575efd289200a5c9574dbccb98b2bd71ef9b4e
