<?php

namespace ConsultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionBookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionBookmarkRepository extends EntityRepository
{
}
