<?php

namespace ConsultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionTagRepository extends EntityRepository
{
}
