<?php

namespace ConsultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionViewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionViewsRepository extends EntityRepository
{
}
