<?php

namespace ConsultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * userInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userInfoRepository extends EntityRepository
{
}
