questions:
    resource: ConsultBundle\Controller\QuestionsController
    type:     rest

privateQuestions:
    resource: ConsultBundle\Controller\PrivateThreadController
    type:     rest

questionComments:
    resource: ConsultBundle\Controller\QuestionCommentsController
    type:     rest

doctorQuestions:
   resource: ConsultBundle\Controller\DoctorQuestionsController
   type:     rest


replies:
    resource: ConsultBundle\Controller\RepliesController
    type:      rest


users:
    resource: ConsultBundle\Controller\UserController
    type:      rest

notification:
    resource: ConsultBundle\Controller\NotificationController
    type:      rest

moderation:
    resource: ConsultBundle\Controller\ModerationController
    type:      rest

master:
    resource: ConsultBundle\Controller\MasterController
    type:      rest

doctor:
    resource: ConsultBundle\Controller\DoctorController
    type:      rest
