questions:
    resource: ConsultBundle\Controller\QuestionsController
    type:     rest

questionComments:
    resource: ConsultBundle\Controller\QuestionCommentsController
    type:     rest

doctorQuestions:
   resource: ConsultBundle\Controller\DoctorQuestionsController
   type:     rest


replies:
    resource: ConsultBundle\Controller\RepliesController
    type:      rest


users:
    resource: ConsultBundle\Controller\UserController
    type:      rest

notification:
    resource: ConsultBundle\Controller\NotificationController
    type:      rest
<<<<<<< HEAD

moderation:
    resource: ConsultBundle\Controller\ModerationController
    type:      rest
||||||| merged common ancestors
=======

master:
    resource: ConsultBundle\Controller\MasterController
    type:      rest
>>>>>>> 4b9180e668ed20fb404b121303138560c12a3286
