questions:
    resource: ConsultBundle\Controller\QuestionsController
    type:     rest

questionComments:
    resource: ConsultBundle\Controller\QuestionCommentsController
    type:     rest

doctorQuestions:
   resource: ConsultBundle\Controller\DoctorQuestionsController
   type:     rest


replies:
    resource: ConsultBundle\Controller\RepliesController
    type:      rest


users:
    resource: ConsultBundle\Controller\UserController
    type:      rest
