questions:
    resource: ConsultBundle\Controller\QuestionsController
    type:     rest

questionBookmarks:
    resource: ConsultBundle\Controller\QuestionBookmarkController
    type:     rest

doctorQuestions:
   resource: ConsultBundle\Controller\DoctorQuestionsController
   type:     rest


replies:
    resource: ConsultBundle\Controller\RepliesController
    type:      rest

users:
    resource: ConsultBundle\Controller\UserController
    type:      rest

keep:
    resource: ConsultBundle\Controller\KeepController
    type:      rest
