parameters:
    # Overriding Security Bundle's Access Listener class to provide detailed
    # error message
services:
    consult.question_manager:
        class: ConsultBundle\Manager\QuestionManager
        arguments:
          - @doctrine
          - @validator
    consult.question_image_manager:
        class: ConsultBundle\Manager\QuestionImageManager
        arguments:
          - @validator