parameters:
    # Overriding Security Bundle's Access Listener class to provide detailed
    # error message
services:

    consult.questionValidator:
        class: ConsultBundle\Validator\QuestionValidator

    consult.questionImageValidator:
         class: ConsultBundle\Validator\QuestionImageValidator

    consult.questionBookmarkValidator:
                 class: ConsultBundle\Validator\QuestionBookmarkValidator

    consult.doctorReplyValidator:
         class: ConsultBundle\Validator\DoctorReplyValidator

    consult.doctorQuestionValidator:
         class: ConsultBundle\Validator\DoctorQuestionValidator

    consult.cacheUtil:
        class: ConsultBundle\Utility\CacheUtils

    consult.helper:
        class: ConsultBundle\Helper\Helper
        arguments:
        - @doctrine
        - @consult.cacheUtil

    consult.question_manager:
        class: ConsultBundle\Manager\QuestionManager
        calls:
          - [setValidator, ["@consult.questionValidator"]]
          - [setHelper, ["@consult.helper"]]
        arguments:
          - @consult.question_image_manager
          - @consult.question_bookmark_manager

    consult.question_image_manager:
        class: ConsultBundle\Manager\QuestionImageManager
        calls:
                  - [setValidator, ["@consult.questionImageValidator"]]
                  - [setHelper, ["@consult.helper"]]

    consult.question_bookmark_manager:
        class: ConsultBundle\Manager\QuestionBookmarkManager
        calls:
                  - [setValidator, ["@consult.questionBookmarkValidator"]]
                  - [setHelper, ["@consult.helper"]]
        arguments:
          - @validator




    consult.doctorReplyManager:
        class: ConsultBundle\Manager\DoctorReplyManager
        calls:
                          - [setValidator, ["@consult.doctorReplyValidator"]]
                          - [setHelper, ["@consult.helper"]]

    consult.doctorQuestionManager:
        class: ConsultBundle\Manager\DoctorQuestionManager
        calls:
                          - [setValidator, ["@consult.doctorQuestionValidator"]]
                          - [setHelper, ["@consult.helper"]]



consult.queue:
        class: ConsultBundle\Queue\AbstractQueue
        factory_service: consult.queue_factory
        factory_method: get
        calls:
          - [ setFabricDomain, ['@?consult.fabric_domain=']]
    consult.queue_factory:
        class: ConsultBundle\Queue\QueueFactory
        calls:
            - [ setContainer, [ @service_container ]]
