parameters:
    # Overriding Security Bundle's Access Listener class to provide detailed
    # error message
services:

    consult.questionValidator:
        class: ConsultBundle\Validator\QuestionValidator
        arguments:
          - @validator

    consult.questionImageValidator:
         class: ConsultBundle\Validator\QuestionImageValidator

    consult.questionBookmarkValidator:
                 class: ConsultBundle\Validator\QuestionBookmarkValidator

    consult.doctorReplyValidator:
         class: ConsultBundle\Validator\DoctorReplyValidator

    consult.doctorQuestionValidator:
         class: ConsultBundle\Validator\DoctorQuestionValidator

    consult.cacheUtil:
        class: ConsultBundle\Utility\CacheUtils

    consult.fileUploadUtil:
        class: ConsultBundle\Utility\FileUploadUtil
        arguments:
        - %s3_access_key%
        - %s3_access_secret%
        - %region%
        - %scheme%
        - %s3_resources_bucket%
        - %fileName%
        - %tempUrl%


    consult.helper:
        class: ConsultBundle\Helper\Helper
        arguments:
        - @doctrine
        - @consult.cacheUtil

    consult.question_manager:
        class: ConsultBundle\Manager\QuestionManager
        calls:
          - [setValidator, ["@consult.questionValidator"]]
          - [setHelper, ["@consult.helper"]]
        arguments:
          - @consult.question_image_manager
          - @consult.question_bookmark_manager

    consult.question_image_manager:
        class: ConsultBundle\Manager\QuestionImageManager
        arguments:
                  - @consult.fileUploadUtil
        calls:
                  - [setValidator, ["@consult.questionImageValidator"]]
                  - [setHelper, ["@consult.helper"]]

    consult.question_bookmark_manager:
        class: ConsultBundle\Manager\QuestionBookmarkManager
        calls:
                  - [setValidator, ["@consult.questionBookmarkValidator"]]
                  - [setHelper, ["@consult.helper"]]
        arguments:
          - @validator




    consult.doctorReplyManager:
        class: ConsultBundle\Manager\DoctorReplyManager
        calls:
                          - [setValidator, ["@consult.doctorReplyValidator"]]
                          - [setHelper, ["@consult.helper"]]

    consult.doctorQuestionManager:
        class: ConsultBundle\Manager\DoctorQuestionManager
        calls:
                          - [setValidator, ["@consult.doctorQuestionValidator"]]
                          - [setHelper, ["@consult.helper"]]

    consult.user_manager:
        class: ConsultBundle\Manager\UserManager
        calls:
            - [setHelper, ["@consult.helper"]]







   # elasticsearch:
        class: Elasticsearch\Client
        arguments:
            - hosts: %elasticsearch_hosts%
              logPath: %kernel.logs_dir%/elasticsearch.log

    consult.consult_domain:
      class: ConsultBundle\ConsultDomain
      scope: request
      arguments: [@request]
      synchronized: true

    consult.consult_queue_factory:
      class: ConsultBundle\Queue\QueueFactory
      calls:
        - [ setContainer, [ @service_container ]]
    consult.consult_queue:
      class: ConsultBundle\Queue\AbstractQueue
      factory_service: consult.consult_queue_factory
      factory_method: get
      calls:
        - [ setConsultDomain, ['@?consult.consult_domain=']]

