parameters:
    # Overriding Security Bundle's Access Listener class to provide detailed
    # error message
services:

    consult.questionValidator:
        class: ConsultBundle\Validator\QuestionValidator
        arguments:
          - @validator

    consult.userValidator:
        class: ConsultBundle\Validator\UserValidator
        arguments:
          - @validator

    consult.questionCommentValidator:
        class: ConsultBundle\Validator\QuestionCommentValidator
        arguments:
          - @validator

    consult.questionImageValidator:
         class: ConsultBundle\Validator\QuestionImageValidator

    consult.questionBookmarkValidator:
        class: ConsultBundle\Validator\QuestionBookmarkValidator
        arguments:
          - @validator

    consult.doctorReplyValidator:
         class: ConsultBundle\Validator\DoctorReplyValidator

    consult.doctorQuestionValidator:
         class: ConsultBundle\Validator\DoctorQuestionValidator
         arguments:
           - @validator

  #  consult.cacheUtil:
  #      class: ConsultBundle\Utility\CacheUtils

    consult.fileUploadUtil:
        class: ConsultBundle\Utility\FileUploadUtil
        arguments:
        - %s3_access_key%
        - %s3_access_secret%
        - %region%
        - %scheme%
        - %s3_resources_bucket%
        - %fileName%
        - %tempUrl%


    consult.helper:
        class: ConsultBundle\Helper\Helper
        arguments:
        - @doctrine
        - @logger

    consult.question_manager:
        class: ConsultBundle\Manager\QuestionManager
        calls:
          - [setValidator, ["@consult.questionValidator"]]
          - [setHelper, ["@consult.helper"]]
        arguments:
          - @consult.user_manager
          - @consult.consult_queue
          - @consult.retrieve_user_profile_util
          - @consult.retrieve_doctor_profile_util
          - @consult.question_bookmark_manager

    consult.question_image_manager:
        class: ConsultBundle\Manager\QuestionImageManager
        arguments:
                  - @consult.fileUploadUtil
        calls:
                  - [setValidator, ["@consult.questionImageValidator"]]
                  - [setHelper, ["@consult.helper"]]

    consult.question_bookmark_manager:
        class: ConsultBundle\Manager\QuestionBookmarkManager
        calls:
                  - [setValidator, ["@consult.questionBookmarkValidator"]]
                  - [setHelper, ["@consult.helper"]]

    consult.doctorReplyManager:
        class: ConsultBundle\Manager\DoctorReplyManager
        calls:
                          - [setValidator, ["@consult.doctorReplyValidator"]]
                          - [setHelper, ["@consult.helper"]]
        arguments:
          - @consult.consult_queue
          - @consult.notification_manager

    consult.doctorQuestionManager:
        class: ConsultBundle\Manager\DoctorQuestionManager
        calls:
                          - [setValidator, ["@consult.doctorQuestionValidator"]]
                          - [setHelper, ["@consult.helper"]]
        arguments:
          - @consult.notification_manager
          - @consult.retrieve_user_profile_util
          - @consult.retrieve_doctor_profile_util

    consult.user_manager:
        class: ConsultBundle\Manager\UserManager
        calls:
            - [setHelper, ["@consult.helper"]]
            - [setValidator, ["@consult.UserValidator"]]
        arguments:
          - @consult.update_accounts_util

    consult.user_profile_manager:
        class: ConsultBundle\Manager\UserProfileManager
        calls:
            - [setHelper, ["@consult.helper"]]
    #        - [setValidator, ["@consult.UserValidator"]]

    consult.question_comment_manager:
        class: ConsultBundle\Manager\QuestionCommentsManager
        calls:
            - [setValidator, ["@consult.questionCommentValidator"]]
            - [setHelper, ["@consult.helper"]]

    consult.account_authenticator_util:
        class: ConsultBundle\Utility\AuthenticationUtils
        arguments:
             - %accounts_host%



    consult.retrieve_user_profile_util:
        class: ConsultBundle\Utility\RetrieveUserProfileUtil
        arguments:
             - %accounts_host%
             - %accounts_signing_key%


    consult.retrieve_doctor_profile_util:
        class: ConsultBundle\Utility\RetrieveDoctorProfileUtil



    consult.update_accounts_util:
        class: ConsultBundle\Utility\UpdateAccountsUtil
        arguments:
             - %accounts_host%









   # elasticsearch:
        class: Elasticsearch\Client
        arguments:
            - hosts: %elasticsearch_hosts%
              logPath: %kernel.logs_dir%/elasticsearch.log

    consult.consult_domain:
      class: ConsultBundle\ConsultDomain
      scope: request
      arguments: [@request]
      synchronized: true

    consult.consult_queue_factory:
      class: ConsultBundle\Queue\QueueFactory
      calls:
        - [ setContainer, [ @service_container ]]
    consult.consult_queue:
      class: ConsultBundle\Queue\AbstractQueue
      factory_service: consult.consult_queue_factory
      factory_method: get
      calls:
        - [ setConsultDomain, ['@?consult.consult_domain=']]


    consult.redis:
        class: ConsultBundle\Manager\RedisClient
        arguments:
            - @snc_redis.default

    consult.classification:
        class: ConsultBundle\Manager\ClassificationManager
        arguments:
             - @consult.redis


    consult.notification_manager:
        class: ConsultBundle\Manager\NotificationManager
        calls:
            - [setHelper, ["@consult.helper"]]

    consult.master_manager:
        class: ConsultBundle\Manager\MasterManager
        calls:
            - [setHelper, ["@consult.helper"]]
